# Generated by Django 4.0.6 on 2022-10-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amoldy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
