# Generated by Django 4.0.6 on 2022-10-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amoldy_app', '0002_categories_remove_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
